name: svg_assets_generator
description: SVG assets generator.
repository: https://github.com/VadimMalykhin/svg_assets_generator
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.10.1

dependencies:
  code_builder: ^4.11.0
  dart_style: ^3.1.3
  path: ^1.9.1
  xml: ^6.6.1
  yaml: ^3.1.3

dependency_overrides:
  lints: any

dev_dependencies:
  lints: ^6.0.0
