name: svg_assets_generator
description: SVG assets generator.
repository: https://github.com/VadimMalykhin/svg_assets_generator

environment:
  sdk: ^3.5.4

dependencies:
  code_builder: ^4.10.1
  dart_style: ^2.3.7
  path: ^1.9.1
  xml: ^6.5.0
  yaml: ^3.1.2

dependency_overrides:
  lints: any

dev_dependencies:
  lints: ^5.1.0
  # source_gen: ^1.5.0
  test: ^1.25.8
